#!/bin/bash
NVCC="nvcc --expt-extended-lambda -std=c++11 -Wno-deprecated-gpu-targets"
INCLUDES="-Ilibs/moderngpu/src -Ilibs/curand-done-right/src -I. -Ilibs/json/src"
OPENGL_LIBS="-lGL -lglut -lGLU"

$NVCC main.cu -o bin/scene $OPENGL_LIBS $INCLUDES
